using System.Collections.Generic;
using NovaStriker.Combat;
using NovaStriker.Core;
using UnityEngine;

namespace NovaStriker.Player
{
    /// <summary>
    /// Damage generated by Velocity Break and Powerslide traversal.
    /// Kept separate from NovaMotor2D so locomotion remains usable without
    /// combat and presentation systems.
    /// </summary>
    public sealed class NovaTraversalDamage : MonoBehaviour
    {
        [SerializeField] private NovaMotor2D motor;
        [SerializeField] private Collider2D bodyCollider;
        [SerializeField] private LayerMask damageableMask;

        private readonly List<Collider2D> overlaps = new(16);
        private readonly HashSet<int> hitTargets = new();

        private ContactFilter2D damageFilter;
        private bool wasDashing;
        private bool wasSliding;

        private void Reset()
        {
            motor = GetComponent<NovaMotor2D>();
            bodyCollider = GetComponent<Collider2D>();
        }

        private void Awake()
        {
            if (!motor)
                motor = GetComponent<NovaMotor2D>();

            if (!bodyCollider)
                bodyCollider = GetComponent<Collider2D>();

            damageFilter = new ContactFilter2D
            {
                useTriggers = true
            };
            damageFilter.SetLayerMask(damageableMask);
        }

        private void FixedUpdate()
        {
            if (!motor || !bodyCollider)
                return;

            bool dashing = motor.IsDashing;
            bool sliding = motor.IsSliding;

            if (
                (dashing && !wasDashing) ||
                (sliding && !wasSliding)
            )
            {
                hitTargets.Clear();
            }

            if (sliding)
            {
                ApplyTraversalHits(
                    motor.ActiveSlideTier,
                    true
                );
            }
            else if (
                dashing &&
                motor.ActiveDashTier ==
                ChargeTier.VelocityBreak
            )
            {
                ApplyTraversalHits(
                    motor.ActiveDashTier,
                    false
                );
            }

            wasDashing = dashing;
            wasSliding = sliding;
        }

        private void ApplyTraversalHits(
            ChargeTier tier,
            bool slide)
        {
            overlaps.Clear();

            int count = bodyCollider.Overlap(
                damageFilter,
                overlaps
            );

            for (int i = 0; i < count; i++)
            {
                Damageable2D target =
                    overlaps[i].GetComponentInParent<Damageable2D>();

                if (!target)
                    continue;

                int id = target.GetInstanceID();

                if (!hitTargets.Add(id))
                    continue;

                int numericTier = (int)tier;

                float damage = slide
                    ? 12f + numericTier * 6f
                    : 24f;

                float horizontal =
                    (180f + numericTier * 70f) /
                    50f;

                Vector2 knockback = new(
                    motor.Facing * horizontal,
                    1.8f
                );

                bool applied = target.ApplyDamage(new DamagePacket(
                    damage,
                    knockback,
                    target.transform.position,
                    CombatFaction.Player,
                    motor.PlayerId,
                    numericTier,
                    slide ? "powerslide" : "velocity-break"
                ));

                if (!applied)
                    continue;

                GameplayEventHub.Raise(new GameplayCue(
                    slide
                        ? GameplayCueType.SlideHit
                        : GameplayCueType.DashHit,
                    motor.PlayerId,
                    target.transform.position,
                    knockback.normalized,
                    numericTier,
                    damage,
                    slide ? "powerslide" : "velocity-break"
                ));
            }
        }
    }
}
